# Generated by Django 4.0.4 on 2022-06-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=150, verbose_name='Source Text')),
                ('target', models.CharField(max_length=150, verbose_name='Target Text')),
                ('source_lang', models.CharField(choices=[('eng', 'English'), ('ass', 'Assamese'), ('ben', 'Bengali'), ('bod', 'Bodo'), ('dog', 'Dogri'), ('guj', 'Gujarati'), ('hin', 'Hindi'), ('kan', 'Kannada'), ('kas', 'Kashmiri'), ('kon', 'Konkani'), ('mai', 'Maithili'), ('mal', 'Malayalam'), ('man', 'Manipuri'), ('mar', 'Marathi'), ('nep', 'Nepali'), ('odi', 'Odia'), ('pun', 'Punjabi'), ('san', 'Sanskrit'), ('sat', 'Santali'), ('sin', 'Sindhi'), ('sih', 'Sinhala'), ('tam', 'Tamil'), ('tel', 'Telugu'), ('urd', 'Urdu')], max_length=3, verbose_name='Source Language')),
                ('target_lang', models.CharField(choices=[('eng', 'English'), ('ass', 'Assamese'), ('ben', 'Bengali'), ('bod', 'Bodo'), ('dog', 'Dogri'), ('guj', 'Gujarati'), ('hin', 'Hindi'), ('kan', 'Kannada'), ('kas', 'Kashmiri'), ('kon', 'Konkani'), ('mai', 'Maithili'), ('mal', 'Malayalam'), ('man', 'Manipuri'), ('mar', 'Marathi'), ('nep', 'Nepali'), ('odi', 'Odia'), ('pun', 'Punjabi'), ('san', 'Sanskrit'), ('sat', 'Santali'), ('sin', 'Sindhi'), ('sih', 'Sinhala'), ('tam', 'Tamil'), ('tel', 'Telugu'), ('urd', 'Urdu')], max_length=3, verbose_name='Target Language')),
                ('domain', models.CharField(choices=[('gen', 'General'), ('leg', 'Legal'), ('edu', 'Education')], default='gen', max_length=3, verbose_name='Text Domain')),
                ('collection_src', models.CharField(max_length=100, verbose_name='Collection Source')),
                ('level', models.CharField(choices=[('w', 'Word Level'), ('p', 'Phrase Level'), ('s', 'Sentence Level')], max_length=1, verbose_name='Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
