# Generated by Django 4.0.5 on 2022-07-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary',
            options={'ordering': ('-created_at',), 'verbose_name': 'Glossary', 'verbose_name_plural': 'Glossaries'},
        ),
        migrations.AlterField(
            model_name='glossary',
            name='source_lang',
            field=models.CharField(choices=[('en', 'English'), ('as', 'Assamese'), ('bn', 'Bengali'), ('bd', 'Bodo'), ('do', 'Dogri'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ks', 'Kashmiri'), ('ko', 'Konkani'), ('ma', 'Maithili'), ('ml', 'Malayalam'), ('mn', 'Manipuri'), ('mr', 'Marathi'), ('np', 'Nepali'), ('od', 'Odia'), ('pa', 'Punjabi'), ('sn', 'Sanskrit'), ('st', 'Santali'), ('si', 'Sindhi'), ('sh', 'Sinhala'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ur', 'Urdu')], max_length=2, verbose_name='Source Language'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='target_lang',
            field=models.CharField(choices=[('en', 'English'), ('as', 'Assamese'), ('bn', 'Bengali'), ('bd', 'Bodo'), ('do', 'Dogri'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ks', 'Kashmiri'), ('ko', 'Konkani'), ('ma', 'Maithili'), ('ml', 'Malayalam'), ('mn', 'Manipuri'), ('mr', 'Marathi'), ('np', 'Nepali'), ('od', 'Odia'), ('pa', 'Punjabi'), ('sn', 'Sanskrit'), ('st', 'Santali'), ('si', 'Sindhi'), ('sh', 'Sinhala'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ur', 'Urdu')], max_length=2, verbose_name='Target Language'),
        ),
    ]
