const constants = {
    APISTATUS: "APISTATUS",
    LOG_IN: "LOG_IN",
    UPLOAD_GLOSSARY_FILE: "UPLOAD_GLOSSARY_FILE",
    ADD_INDIVIDUAL_GLOSSARY: "ADD_INDIVIDUAL_GLOSSARY",
    SEARCH_GLOSSARY: "SEARCH_GLOSSARY",
    GET_ALL_LANGUAGE: "GET_ALL_LANGUAGE",
    GET_ALL_DOMAINS: "GET_ALL_DOMAINS",
}

export default constants;